### ISSUE TITLE
Not maintained?

### ISSUE THREAD

**Issue by edwinvdpol** [asantibanez/livewire-resource-time-grid#2]
It is too bad this repo doesn't get updated and/or maintained. There could be a lot of potential for this library, also in combination with the calendar library (and visa versa of course). ([fullcalendar](https://fullcalendar.io/), only for Laravel :wink: )

**Comment by barryvdh** [comment]
I've submitted #3 and #4 to bring it up to date with the latest Livewire :)

**Comment by asantibanez** [comment]
Thanks @edwinvdpol @barryvdh for your interest in the package. I've just updated it to Livewire v2 and added support to L8 thanks to #3 

Enjoy!
