### ISSUE TITLE
Is problems with version of PHP extension

### ISSUE THREAD

**Issue by adamovich-ivan** [asantibanez/livewire-resource-time-grid#7]
after install on clean Laravel Homestead is error: Package asantibanez/livewire-resource-time-grid has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

**Comment by fwartner** [comment]
I opened up a PR for this issue.

See https://github.com/asantibanez/livewire-resource-time-grid/pull/8

**Comment by fwartner** [comment]
Since it's merged, i think @asantibanez can close this issue.
